stages:
  train:
    cmd: python src/Model_seg.py
    deps:
      - src/Model_seg.py
      - src/data.py
      - src/losses.py
      - processed_data/
      - params.yaml
    params:
      - model_seg
    outs:
      - checkpoints/seg_best.h5

  inference:
    cmd: python src/predict_and_stack.py
    deps:
      - src/predict_and_stack.py
      - checkpoints/seg_best.h5
      - processed_data/Test_data/Images/
    outs:
      - predictions_3d/

  export_nifti:
    cmd: python src/export_nifti.py
    deps:
      - src/export_nifti.py
      - predictions_3d/
    outs:
      - nifti_outputs/
