stages:
  train:
    cmd: PYTHONPATH=. python src/Model_seg.py
    deps:
      - src/Model_seg.py
      - src/data.py
      - src/losses.py
      - processed_data/
      - params.yaml
    params:
      - model_seg
    outs:
      - checkpoints/seg_best.h5

  evaluate:
    cmd: PYTHONPATH=. python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - src/data.py
      - src/losses.py
      - checkpoints/seg_best.h5
      - processed_data/
    outs:
      - test_metrics.json

  inference:
    cmd: PYTHONPATH=. python src/predict_and_stack.py
    deps:
      - src/predict_and_stack.py
      - checkpoints/seg_best.h5
      - processed_data/Test_data/
    outs:
      - predictions_3d/

  export_nifti:
    cmd: python src/export_nifti.py
    deps:
      - src/export_nifti.py
      - predictions_3d/
    outs:
      - nifti_outputs/
