name: CerebraScan CI

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.ci -t cerebra-ci .

      - name: Run container
        run: docker run -d -p 8001:8001 cerebra-ci

      - name: Wait for server
        run: sleep 10

      - name: Test Root API
        run: curl http://localhost:8001 || exit 1

      - name: Test Upload Endpoint
        run: |
          echo "dummy" > test.txt
          zip test.zip test.txt

          curl -X POST http://localhost:8001/upload \
          -F "file=@test.zip"

      - name: Test Analyze Route (validation)
        run: |
          curl -X POST http://localhost:8001/analyze \
          -H "Content-Type: application/json" \
          -d '{"upload_id": "fake_id"}'

      - name: Test Report Route
        run: |
          curl http://localhost:8001/generate-report/fake_id
